### PR TITLE
Disable Designer plugin when built as a subproject.

### PR DESCRIPTION
**Pull request by ChinouneMehdi**

### CODE REVIEW

**Comment by highperformancecoder** [comment]
Thanks. I've just pushed a commit that does exactly that, but drives it from SciDaVis's files.

Also had to disable the install steps for cross-compiling, but the
good news is I've finally got SciDaVis to build under MXE, so I can
now do Windows releases!

Thanks for all this work with cmake - it definitely improves things.

On Mon, Feb 08, 2021 at 08:39:11PM -0800, مهدي شينون (Mehdi Chinoune) wrote:
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/SciDAVis/qwt5-qt5/pull/3
> 
> Commit Summary
> 
>   • Disable Designer plugin when built as a subproject.
> 
> File Changes
> 
>   • M CMakeLists.txt (14)
> 
> Patch Links:
> 
>   • https://github.com/SciDAVis/qwt5-qt5/pull/3.patch
>   • https://github.com/SciDAVis/qwt5-qt5/pull/3.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by ChinouneMehdi** [comment]
> Thanks. I've just pushed a commit that does exactly that, but drives it from SciDaVis's files. Also had to disable the install steps for cross-compiling, but the good news is I've finally got SciDaVis to build under MXE, so I can now do Windows releases! Thanks for all this work with cmake - it definitely improves things.

Why not using the github-action that I have submitted to build with msi installer natively, download it, sign it and then reupload it to sourceforge?

**Comment by highperformancecoder** [comment]
On Mon, Feb 08, 2021 at 08:53:11PM -0800, مهدي شينون (Mehdi Chinoune) wrote:
>     Thanks. I've just pushed a commit that does exactly that, but drives it
>     from SciDaVis's files. Also had to disable the install steps for
>     cross-compiling, but the good news is I've finally got SciDaVis to build
>     under MXE, so I can now do Windows releases! Thanks for all this work with
>     cmake - it definitely improves things.
> 
> Why not using the github-action that I have submitted to build with msi
> installer natively, download it, sign it and then reupload it to sourceforge?

Mainly because when I tried that:

a) the zip file didn't have a containing folder, which made the whole release process horribly manual
b) at the time, we didn't have msi generation, only a .exe
c) Installing the full .net environment to run wix on github actions looked daunting to me.

Now that you have .msi files being created on github, if we could
arrange code signing as a github action as well, then that will be a
good way of creating distributables. I would then just copy the signed
artifact directly to SourceForge and call it a day.

At the moment, I'd still prefer the MXE, copy to windows and run the
Wix script (which includes codesigning), which is very similar to the
work process I use on another project. Using github actions currently
doesn't save any time or effort, as I'd still have to unpack the zip
file, copy it to windows, code sign, check install, copy back then
upload.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by ChinouneMehdi** [comment]
> On Mon, Feb 08, 2021 at 08:53:11PM -0800, مهدي شينون (Mehdi Chinoune) wrote: Thanks. I've just pushed a commit that does exactly that, but drives it from SciDaVis's files. Also had to disable the install steps for cross-compiling, but the good news is I've finally got SciDaVis to build under MXE, so I can now do Windows releases! Thanks for all this work with cmake - it definitely improves things. Why not using the github-action that I have submitted to build with msi installer natively, download it, sign it and then reupload it to sourceforge?
> Mainly because when I tried that: a) the zip file didn't have a containing folder, which made the whole release process horribly manual b) at the time, we didn't have msi generation, only a .exe c) Installing the full .net environment to run wix on github actions looked daunting to me. Now that you have .msi files being created on github, if we could arrange code signing as a github action as well, then that will be a good way of creating distributables. I would then just copy the signed artifact directly to SourceForge and call it a day. At the moment, I'd still prefer the MXE, copy to windows and run the Wix script (which includes codesigning), which is very similar to the work process I use on another project. Using github actions currently doesn't save any time or effort, as I'd still have to unpack the zip file, copy it to windows, code sign, check install, copy back then upload.
> […](#)
> --
> ---------------------------------------------------------------------------- Dr Russell Standish Phone 0425 253119 (mobile) Principal, High Performance Coders hpcoder@hpcoders.com.au http://www.hpcoders.com.au ----------------------------------------------------------------------------
Just to clarify,
1- The github-action that I have setup is different from github artifacts, the action upload the installers directly to the release page as they are. without putting them in a zip file.
2- for the code-signing that's up to you to configure in your repository using secrets.
3- There is no need to install anything nor .NET neither Wix, both are preinstalled in the github-image.
4- I am talking about packaging.yml which I was configured to be trigged when you push a tag.

**Pull request merged**
